version: "3"

services:
    influxdb:
        image: influxdb:1.6.1
        ports:
            - "8086:8086"
            - "8083:8083"
        volumes:
            - $PWD/influxdb:/var/lib/influxdb
            - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro
        restart: always
    sensors:
        depends_on:
            - influxdb
        build: sensor_reader
        privileged: true
        restart: always
    grafana:
        depends_on:
            - influxdb
            - sensors
        image: fg2it/grafana-armhf:v5.0.4
        ports:
            - "3000:3000"
        environment:
            - GF_INSTALL_PLUGINS=grafana-clock-panel
        volumes:
            - $PWD/grafana:/var/lib/grafana
        restart: always

