version: "3"

services:
    influxdb:
        image: influxdb:1.8
        ports:
            - "8086:8086"
        networks:
            - sensornet
        volumes:
            - influxdata:/var/lib/influxdb
            - $PWD/influxdb.conf:/etc/influxdb/influxdb.conf:ro
        restart: always
    sensors:
        depends_on:
            - influxdb
        build: .
        privileged: true
        environment:
            - INFLUX_HOST='influxdb'
        networks:
            - sensornet
        restart: always

networks:
    sensornet:
volumes:
    influxdata:
        external: true